import 'field_position.dart';

class Formations {
  static const Map<String, List<FieldPosition>> data = {
    "4-3-3": [
      FieldPosition(
        id: "GK",
        name: "Portero",
        x: 0.50,
        y: 0.92,
      ),
      FieldPosition(
        id: "LB",
        name: "Lateral Izquierdo",
        x: 0.12,
        y: 0.78,
      ),
      FieldPosition(
        id: "LCB",
        name: "Central Izquierdo",
        x: 0.37,
        y: 0.75,
      ),
      FieldPosition(
        id: "RCB",
        name: "Central Derecho",
        x: 0.63,
        y: 0.75,
      ),
      FieldPosition(
        id: "RB",
        name: "Lateral Derecho",
        x: 0.88,
        y: 0.78,
      ),
      FieldPosition(
        id: "LCM",
        name: "Interior Izquierdo",
        x: 0.25,
        y: 0.50,
      ),
      FieldPosition(
        id: "CM",
        name: "Mediocentro",
        x: 0.50,
        y: 0.45,
      ),
      FieldPosition(
        id: "RCM",
        name: "Interior Derecho",
        x: 0.75,
        y: 0.50,
      ),
      FieldPosition(
        id: "LW",
        name: "Extremo Izquierdo",
        x: 0.15,
        y: 0.18,
      ),
      FieldPosition(
        id: "ST",
        name: "Delantero Centro",
        x: 0.50,
        y: 0.08,
      ),
      FieldPosition(
        id: "RW",
        name: "Extremo Derecho",
        x: 0.85,
        y: 0.18,
      ),
    ],

    "4-4-2": [
      FieldPosition(
        id: "GK",
        name: "Portero",
        x: 0.50,
        y: 0.92,
      ),
      FieldPosition(
        id: "LB",
        name: "Lateral Izquierdo",
        x: 0.12,
        y: 0.78,
      ),
      FieldPosition(
        id: "LCB",
        name: "Central Izquierdo",
        x: 0.37,
        y: 0.75,
      ),
      FieldPosition(
        id: "RCB",
        name: "Central Derecho",
        x: 0.63,
        y: 0.75,
      ),
      FieldPosition(
        id: "RB",
        name: "Lateral Derecho",
        x: 0.88,
        y: 0.78,
      ),
      FieldPosition(
        id: "LM",
        name: "Interior Izquierdo",
        x: 0.15,
        y: 0.50,
      ),
      FieldPosition(
        id: "LCM",
        name: "Mediocentro Izquierdo",
        x: 0.38,
        y: 0.48,
      ),
            FieldPosition(
        id: "RCM",
        name: "Mediocentro Derecho",
        x: 0.62,
        y: 0.48,
      ),
      FieldPosition(
        id: "RM",
        name: "Interior Derecho",
        x: 0.85,
        y: 0.50,
      ),
      FieldPosition(
        id: "LS",
        name: "Delantero Izquierdo",
        x: 0.35,
        y: 0.14,
      ),
      FieldPosition(
        id: "RS",
        name: "Delantero Derecho",
        x: 0.65,
        y: 0.14,
      ),
    ],

    "4-2-3-1": [
      FieldPosition(
        id: "GK",
        name: "Portero",
        x: 0.50,
        y: 0.92,
      ),
      FieldPosition(
        id: "LB",
        name: "Lateral Izquierdo",
        x: 0.12,
        y: 0.78,
      ),
      FieldPosition(
        id: "LCB",
        name: "Central Izquierdo",
        x: 0.37,
        y: 0.75,
      ),
      FieldPosition(
        id: "RCB",
        name: "Central Derecho",
        x: 0.63,
        y: 0.75,
      ),
      FieldPosition(
        id: "RB",
        name: "Lateral Derecho",
        x: 0.88,
        y: 0.78,
      ),
      FieldPosition(
        id: "LDM",
        name: "Pivote Izquierdo",
        x: 0.38,
        y: 0.58,
      ),
      FieldPosition(
        id: "RDM",
        name: "Pivote Derecho",
        x: 0.62,
        y: 0.58,
      ),
      FieldPosition(
        id: "LAM",
        name: "Mediapunta Izquierdo",
        x: 0.18,
        y: 0.34,
      ),
      FieldPosition(
        id: "CAM",
        name: "Mediapunta",
        x: 0.50,
        y: 0.30,
      ),
      FieldPosition(
        id: "RAM",
        name: "Mediapunta Derecho",
        x: 0.82,
        y: 0.34,
      ),
      FieldPosition(
        id: "ST",
        name: "Delantero Centro",
        x: 0.50,
        y: 0.08,
      ),
    ],
    "4-1-4-1": [
      FieldPosition(
        id: "GK",
        name: "Portero",
        x: 0.50,
        y: 0.92,
      ),
      FieldPosition(
        id: "LB",
        name: "Lateral Izquierdo",
        x: 0.12,
        y: 0.78,
      ),
      FieldPosition(
        id: "LCB",
        name: "Central Izquierdo",
        x: 0.37,
        y: 0.75,
      ),
      FieldPosition(
        id: "RCB",
        name: "Central Derecho",
        x: 0.63,
        y: 0.75,
      ),
      FieldPosition(
        id: "RB",
        name: "Lateral Derecho",
        x: 0.88,
        y: 0.78,
      ),
      FieldPosition(
        id: "CDM",
        name: "Pivote",
        x: 0.50,
        y: 0.60,
      ),
      FieldPosition(
        id: "LM",
        name: "Interior Izquierdo",
        x: 0.15,
        y: 0.40,
      ),
      FieldPosition(
        id: "LCM",
        name: "Mediocentro Izquierdo",
        x: 0.38,
        y: 0.36,
      ),
      FieldPosition(
        id: "RCM",
        name: "Mediocentro Derecho",
        x: 0.62,
        y: 0.36,
      ),
      FieldPosition(
        id: "RM",
        name: "Interior Derecho",
        x: 0.85,
        y: 0.40,
      ),
      FieldPosition(
        id: "ST",
        name: "Delantero Centro",
        x: 0.50,
        y: 0.08,
      ),
    ],

    "3-5-2": [
      FieldPosition(
        id: "GK",
        name: "Portero",
        x: 0.50,
        y: 0.92,
      ),
      FieldPosition(
        id: "LCB",
        name: "Central Izquierdo",
        x: 0.22,
        y: 0.78,
      ),
      FieldPosition(
        id: "CB",
        name: "Central",
        x: 0.50,
        y: 0.75,
      ),
      FieldPosition(
        id: "RCB",
        name: "Central Derecho",
        x: 0.78,
        y: 0.78,
      ),
      FieldPosition(
        id: "LWB",
        name: "Carrilero Izquierdo",
        x: 0.05,
        y: 0.50,
      ),
      FieldPosition(
        id: "LCM",
        name: "Interior Izquierdo",
        x: 0.28,
        y: 0.46,
      ),
      FieldPosition(
        id: "CM",
        name: "Mediocentro",
        x: 0.50,
        y: 0.42,
      ),
      FieldPosition(
        id: "RCM",
        name: "Interior Derecho",
        x: 0.72,
        y: 0.46,
      ),
      FieldPosition(
        id: "RWB",
        name: "Carrilero Derecho",
        x: 0.95,
        y: 0.50,
      ),
      FieldPosition(
        id: "LS",
        name: "Delantero Izquierdo",
        x: 0.35,
        y: 0.14,
      ),
      FieldPosition(
        id: "RS",
        name: "Delantero Derecho",
        x: 0.65,
        y: 0.14,
      ),
    ],
    "3-4-3": [
      FieldPosition(
        id: "GK",
        name: "Portero",
        x: 0.50,
        y: 0.92,
      ),
      FieldPosition(
        id: "LCB",
        name: "Central Izquierdo",
        x: 0.22,
        y: 0.78,
      ),
      FieldPosition(
        id: "CB",
        name: "Central",
        x: 0.50,
        y: 0.75,
      ),
      FieldPosition(
        id: "RCB",
        name: "Central Derecho",
        x: 0.78,
        y: 0.78,
      ),
      FieldPosition(
        id: "LM",
        name: "Interior Izquierdo",
        x: 0.12,
        y: 0.48,
      ),
      FieldPosition(
        id: "LCM",
        name: "Mediocentro Izquierdo",
        x: 0.38,
        y: 0.45,
      ),
      FieldPosition(
        id: "RCM",
        name: "Mediocentro Derecho",
        x: 0.62,
        y: 0.45,
      ),
      FieldPosition(
        id: "RM",
        name: "Interior Derecho",
        x: 0.88,
        y: 0.48,
      ),
      FieldPosition(
        id: "LW",
        name: "Extremo Izquierdo",
        x: 0.15,
        y: 0.18,
      ),
      FieldPosition(
        id: "ST",
        name: "Delantero Centro",
        x: 0.50,
        y: 0.08,
      ),
      FieldPosition(
        id: "RW",
        name: "Extremo Derecho",
        x: 0.85,
        y: 0.18,
      ),
    ],

    "5-3-2": [
      FieldPosition(
        id: "GK",
        name: "Portero",
        x: 0.50,
        y: 0.92,
      ),
      FieldPosition(
        id: "LWB",
        name: "Carrilero Izquierdo",
        x: 0.03,
        y: 0.70,
      ),
      FieldPosition(
        id: "LCB",
        name: "Central Izquierdo",
        x: 0.22,
        y: 0.78,
      ),
      FieldPosition(
        id: "CB",
        name: "Central",
        x: 0.50,
        y: 0.75,
      ),
      FieldPosition(
        id: "RCB",
        name: "Central Derecho",
        x: 0.78,
        y: 0.78,
      ),
      FieldPosition(
        id: "RWB",
        name: "Carrilero Derecho",
        x: 0.97,
        y: 0.70,
      ),
      FieldPosition(
        id: "LCM",
        name: "Interior Izquierdo",
        x: 0.25,
        y: 0.48,
      ),
      FieldPosition(
        id: "CM",
        name: "Mediocentro",
        x: 0.50,
        y: 0.42,
      ),
      FieldPosition(
        id: "RCM",
        name: "Interior Derecho",
        x: 0.75,
        y: 0.48,
      ),
      FieldPosition(
        id: "LS",
        name: "Delantero Izquierdo",
        x: 0.35,
        y: 0.14,
      ),
      FieldPosition(
        id: "RS",
        name: "Delantero Derecho",
        x: 0.65,
        y: 0.14,
      ),
    ],
  };
}